query getProfile {
  me {
    id
    name
    email
    avatar
  }
}

query getStoresList {
  getStoresList {
    id
    name
    address
    image
  }
}

query getStore($id: ID!) {
  getStore(id: $id) {
    id
    name
    description
    phone
    image
    cover
    address
    hours
  }
}

query getOrders($search: String, $store_id: ID!, $status: OrderStatus, $page: Int, $orderBy: [QueryGetOrdersOrderByOrderByClause!]) {
  getOrders(store_id: $store_id, page: $page, orderBy: $orderBy, status: $status, search: $search) {
    data {
      id
      no
      status
      total
      created_at
      user {
        id
        name
        avatar
        phone
      }
    }
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}

query getOrder($id: ID!, $store_id: ID!) {
  getOrder(id: $id, store_id: $store_id) {
    id
    status
    no
    total
    duration
    user {
      id
      name
      avatar
      phone
    }
    store {
      id
      name
    }
    items {
      id
      quantity
      price
      data {
        service {
          id
          name
          image
        }
        options {
          id
          name
          price
        }
      }
    }
    created_at
  }
}

query getMenus($store_id: ID!) {
  getMenus(store_id: $store_id) {
    id
    name
    image
    active
    items {
      id
      name
      image
      active
      services {
        id
        name
        image
        price
        active
      }
    }
  }
}

query getService($id: ID!, $store_id: ID!) {
  getService(id: $id, store_id: $store_id) {
    id
    name
    image
    price
    duration
    description
    top
    active
    store_id
    menu_id
    extras {
      id
      multiple
      name
      active
      options {
        id
        name
        price
        duration
        description
        active
        default
      }
    }
  }
}

query getUsers($store_id: ID!, $search: String, $page: Int) {
  getUsers(store_id: $store_id, search: $search, page: $page) {
    data {
      id
      name
      email
      phone
      avatar
      created_at
      active
      birthday
      roles {
        id
        name
      }
    }
    paginatorInfo {
      count
      currentPage
      firstItem
      hasMorePages
      lastItem
      lastPage
      perPage
      total
    }
  }
}

query getUser($id: ID!) {
  getUser(id: $id) {
    id
    name
    email
    phone
    avatar
    birthday
    gender
    active
    storeIds
    created_at
    stores {
      id
      name
      address
    }
    roles {
      id
      name
    }
  }
}


query getUsersList($store_id: ID!) {
  getUsersList(store_id: $store_id) {
    id
    name
  }
}

query getOrdersList($store_id: ID!, $scheduled_at: Date!, $status: OrderStatus) {
  getOrdersList(store_id: $store_id, scheduled_at: $scheduled_at, status: $status) {
    id
    no
    status
    start: scheduled_at
    end: ended_at
    duration
    resourceId: user_id
    user {
      id
      name
    } 
  }
}
